# Generated by Django 5.0.3 on 2024-03-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popular',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
